# Generated by Django 2.2.6 on 2020-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_auto_20200212_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='content',
            field=models.TextField(default='', help_text='Write the content of your page here.'),
        ),
    ]
