# Generated by Django 3.0.4 on 2020-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_userhobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='img_url',
            field=models.URLField(default='https://www.okea.org/wp-content/uploads/2019/10/placeholder.png', max_length=1000),
        ),
    ]
