# Generated by Django 2.2.6 on 2020-02-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_hobbies_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='content',
            field=models.TextField(help_text='Write the description of your hobby here.'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(help_text='Name of your hobby.', max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600),
        ),
    ]
