# Generated by Django 3.0.3 on 2020-02-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_hobbies_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='choice',
            field=models.CharField(default='Attending', max_length=200),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='content',
            field=models.TextField(help_text='Write the description of your hobby here.'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(default='Name of Hobby', help_text='Name of your hobby.', max_length=100, unique=True),
        ),
    ]
