# Generated by Django 3.0.3 on 2020-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_auto_20200219_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(help_text='Name of your hobby.', max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600),
        ),
    ]
