# Generated by Django 3.0.3 on 2020-02-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0006_auto_20200219_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='scheduled_date',
            field=models.DateTimeField(default='Scheduled date'),
        ),
    ]
